service: serverless

provider:
  name: aws
  runtime: nodejs14.x
  # profile: femasters
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:  
  api:
    handler: src/api/api.handler
    events: 
      - http: GET /api
  todos:
    handler: src/api/todos.handler
    
  todo:
    handler: src/api/todo.handler
    
